apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: frontend
  namespace: expense
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: frontend 
      project: expense 
  template: 
    metadata: 
      labels: 
        app: frontend 
        project: expense
    spec: 
      containers: 
      - name: frontend 
        image: santhoshdatti/frontend:1.1.0 
        ports:
        - conatinerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata: 
  name: frontend 
spec:
  type: LoadBalancer 
  selector: 
    app: frontend 
    project: expense 
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 8080