apiVersion: apps/v1 
kind: Deployment 
metadata:   
  name: backend 
  namespace: expense 
spec: 
  replicas: 1 
  selector: 
    matchLabels:
      app: backend
      project: expense 
  template:
    metadata:
      labels:
        app: backend
        project: expense
    spec:
      containers:
      - name: backend
        image: santhoshdatti/backend:1.0.0 

---

apiVersion: v1 
kind: Service 
metadata: 
  name: backend 
spec:
  selector: 
    app: backend 
    project: expense
  ports: 
  - protocol: TCP
    port: 8080
    targetPort: 8080