apiVersion: apps/v1 
kind: Deployment 
metadata:   
  name: backend 
  namespace: expense 
spec: 
  replicas: 1 
  selector: 
    matchLabels:
      app: backend
      project: expense 
  template:
    metadata:
      labels:
        app: backend
        project: expense 
    