apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mysql
  namespace: expense
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      project: expense
  template: 
    metadata:
      labels: 
        app: mysql
        project: expense
    spec:
      containers:
      - name: mysql
        image: santhoshdatti/mysql:1.0.0